BEGIN;

CREATE TABLE IF NOT EXISTS contractor_followups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contractor_id INTEGER NOT NULL,
    compliance_record_id INTEGER,
    followup_date DATE NOT NULL,
    followup_method VARCHAR(20) NOT NULL
        CHECK (followup_method IN ('Email', 'Phone', 'Meeting', 'Text', 'Other')),
    subject VARCHAR(200) NOT NULL,
    notes TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'Open'
        CHECK (status IN ('Open', 'Waiting Response', 'Resolved', 'Closed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_contractor_followups_contractor
        FOREIGN KEY (contractor_id) REFERENCES contractors(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_contractor_followups_compliance_record
        FOREIGN KEY (compliance_record_id) REFERENCES compliance_records(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_contractor_followups_contractor_date
    ON contractor_followups (contractor_id, followup_date DESC, created_at DESC);

ALTER TABLE contractor_followups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS contractor_followups_select_development ON contractor_followups;
CREATE POLICY contractor_followups_select_development
    ON contractor_followups FOR SELECT
    TO anon, authenticated
    USING (TRUE);

DROP POLICY IF EXISTS contractor_followups_insert_development ON contractor_followups;
CREATE POLICY contractor_followups_insert_development
    ON contractor_followups FOR INSERT
    TO anon, authenticated
    WITH CHECK (TRUE);

COMMIT;