BEGIN;

ALTER TABLE contractors
    ADD COLUMN IF NOT EXISTS address_1 TEXT,
    ADD COLUMN IF NOT EXISTS address_2 TEXT,
    ADD COLUMN IF NOT EXISTS city VARCHAR(150),
    ADD COLUMN IF NOT EXISTS state VARCHAR(100),
    ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS nj_pwc_number VARCHAR(100),
    ADD COLUMN IF NOT EXISTS nj_brc_number VARCHAR(100),
    ADD COLUMN IF NOT EXISTS sage_erp_id TEXT,
    ADD COLUMN IF NOT EXISTS brc_name_control VARCHAR(4),
    ADD COLUMN IF NOT EXISTS brc_name_control_is_manual BOOLEAN NOT NULL DEFAULT FALSE;

COMMIT;
