-- =====================================================================
-- NJ PWC contractor search & backfill (Add Contractor workflow)
-- Date: 2026-10-05
--
-- Non-destructive: CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS.
--
-- Adds a search-request store for the ATTENDED Add Contractor "Search
-- NJ PWC" workflow:
--   1) Add form calls a SubTracker server endpoint -> creates a request
--      row here (status 'pending').
--   2) Power Automate Desktop (RPA) polls pending requests, queries the
--      NJ Public Works Power BI report, and POSTs candidate matches back.
--   3) The Add form polls this row and renders the candidates for the
--      user to review and select.
--
-- =====================================================================
-- COMPLIANCE LOGIC LOCK
-- =====================================================================
-- This table stores SEARCH REQUESTS and CANDIDATE MATCHES ONLY. It is
-- never read by dashboard counts, 90/60/30 Day, Expired, Missing
-- Information, contractor status, reports, reminders, or Active
-- Compliance Records. No row here ever writes to Active Compliance
-- Records. Importing a match populates the Add Contractor form fields
-- and (after the contractor is saved) creates a display-only Synced
-- Compliance Record + a pending Review Queue entry.
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.compliance_sync_search_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compliance_name VARCHAR(20) NOT NULL DEFAULT 'NJ PWC'
        CHECK (compliance_name IN ('NJ PWC', 'NJ BRC', 'NY PWC', 'NY BRC')),

    -- Search input (exact-normalized company name for a new contractor
    -- whose NJ PWC number is not yet known)
    searched_company_name VARCHAR(200) NOT NULL,
    searched_zip_code VARCHAR(20),
    searched_city VARCHAR(150),
    searched_state VARCHAR(100),

    -- Request lifecycle: pending -> completed | no_match | failed
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'completed', 'no_match', 'failed')),
    result_status VARCHAR(30)
        CHECK (result_status IS NULL OR result_status IN
            ('Match Found', 'No Match Found', 'Multiple Matches', 'Invalid Search', 'Website Error', 'RPA Error')),

    -- Candidate matches returned by the RPA (0..n). Each element:
    --   { business_name, certificate_number, registration_date,
    --     expiration_date, address, city, state, zip_code, county }
    candidates JSONB NOT NULL DEFAULT '[]'::jsonb,

    -- The candidate the user selected (kept until contractor is saved)
    selected_candidate JSONB,

    -- Attended workflow bookkeeping
    is_test BOOLEAN NOT NULL DEFAULT FALSE,
    requested_by VARCHAR(200),
    error_message TEXT,
    source_url TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_compliance_sync_search_requests_status
    ON public.compliance_sync_search_requests (status, created_at ASC);

-- The RPA polls for pending NJ PWC requests.
CREATE INDEX IF NOT EXISTS idx_compliance_sync_search_requests_pending
    ON public.compliance_sync_search_requests (compliance_name, status)
    WHERE status = 'pending';

-- Development-permissive RLS, consistent with the other compliance_sync
-- tables. Tighten before production if required.
ALTER TABLE public.compliance_sync_search_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS compliance_sync_search_requests_all ON public.compliance_sync_search_requests;
CREATE POLICY compliance_sync_search_requests_all
    ON public.compliance_sync_search_requests
    FOR ALL
    USING (TRUE)
    WITH CHECK (TRUE);

COMMIT;
