BEGIN;

CREATE TABLE IF NOT EXISTS public.user_profiles (
    auth_user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL CHECK (role IN ('Administrator', 'Compliance Manager', 'Project Manager', 'Read Only')),
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
    role TEXT NOT NULL CHECK (role IN ('Administrator', 'Compliance Manager', 'Project Manager', 'Read Only')),
    module TEXT NOT NULL CHECK (module IN ('dashboard', 'contractors', 'compliance', 'insurance', 'followups', 'projects', 'reports', 'imports', 'documents', 'activity', 'users', 'roles', 'audit', 'settings')),
    can_view BOOLEAN NOT NULL DEFAULT FALSE,
    can_manage BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (role, module),
    CHECK (NOT can_manage OR can_view)
);

CREATE TABLE IF NOT EXISTS public.administration_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.user_profiles(auth_user_id) ON DELETE SET NULL,
    user_name TEXT NOT NULL,
    user_email TEXT NOT NULL,
    audit_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    action TEXT NOT NULL,
    object_type TEXT NOT NULL,
    object_id TEXT,
    object_label TEXT NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE INDEX IF NOT EXISTS idx_user_profiles_role_status ON public.user_profiles(role, status);
CREATE INDEX IF NOT EXISTS idx_administration_audit_log_date ON public.administration_audit_log(audit_date DESC);
CREATE INDEX IF NOT EXISTS idx_administration_audit_log_object ON public.administration_audit_log(object_type, object_id);

INSERT INTO public.role_permissions (role, module, can_view, can_manage)
SELECT
    role_name,
    module_name,
    role_name = 'Administrator'
        OR (role_name = 'Compliance Manager' AND module_name = ANY(ARRAY['dashboard', 'contractors', 'compliance', 'insurance', 'followups', 'projects', 'reports', 'imports']))
        OR (role_name IN ('Project Manager', 'Read Only') AND module_name = ANY(ARRAY['dashboard', 'contractors', 'compliance', 'insurance', 'followups', 'projects', 'reports', 'imports', 'documents', 'activity'])),
    role_name = 'Administrator'
        OR (role_name = 'Compliance Manager' AND module_name = ANY(ARRAY['contractors', 'compliance', 'insurance', 'followups', 'projects', 'reports', 'imports']))
FROM (VALUES ('Administrator'), ('Compliance Manager'), ('Project Manager'), ('Read Only')) AS roles(role_name)
CROSS JOIN (VALUES
    ('dashboard'), ('contractors'), ('compliance'), ('insurance'), ('followups'), ('projects'), ('reports'),
    ('imports'), ('documents'), ('activity'), ('users'), ('roles'), ('audit'), ('settings')
) AS modules(module_name)
ON CONFLICT (role, module) DO UPDATE
SET can_view = EXCLUDED.can_view, can_manage = EXCLUDED.can_manage;

CREATE OR REPLACE FUNCTION public.user_has_module_permission(p_module TEXT, p_action TEXT DEFAULT 'view')
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.user_profiles AS profile
        JOIN public.role_permissions AS permission ON permission.role = profile.role
        WHERE profile.auth_user_id = auth.uid()
          AND profile.status = 'Active'
          AND permission.module = p_module
          AND CASE p_action
                WHEN 'view' THEN permission.can_view
                WHEN 'manage' THEN permission.can_manage
                ELSE FALSE
              END
    );
$$;

REVOKE ALL ON FUNCTION public.user_has_module_permission(TEXT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.user_has_module_permission(TEXT, TEXT) TO authenticated;

ALTER VIEW public.contractor_compliance_status SET (security_invoker = true);
REVOKE ALL ON public.contractor_compliance_status FROM anon;
GRANT SELECT ON public.contractor_compliance_status TO authenticated;

ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.administration_audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_profiles_select_self ON public.user_profiles;
CREATE POLICY user_profiles_select_self ON public.user_profiles
    FOR SELECT TO authenticated USING (auth_user_id = auth.uid());

DROP POLICY IF EXISTS role_permissions_select_authenticated ON public.role_permissions;
CREATE POLICY role_permissions_select_authenticated ON public.role_permissions
    FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS administration_audit_select_admin ON public.administration_audit_log;
CREATE POLICY administration_audit_select_admin ON public.administration_audit_log
    FOR SELECT TO authenticated USING (public.user_has_module_permission('audit', 'view'));

REVOKE ALL ON public.user_profiles, public.role_permissions, public.administration_audit_log FROM anon;
GRANT SELECT ON public.user_profiles, public.role_permissions, public.administration_audit_log TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.administration_audit_log_id_seq TO authenticated;

DO $$
DECLARE
    policy_row RECORD;
    table_row RECORD;
BEGIN
    FOR policy_row IN
        SELECT schemaname, tablename, policyname
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = ANY (ARRAY[
              'contractors', 'contractor_insurance', 'contractor_insurance_history', 'projects',
              'contractor_projects', 'contractor_tiered_subs', 'compliance_types', 'compliance_records',
              'documents', 'activity_log', 'contractor_followups', 'reminders', 'import_history'
          ])
    LOOP
        EXECUTE format('DROP POLICY %I ON %I.%I', policy_row.policyname, policy_row.schemaname, policy_row.tablename);
    END LOOP;

    FOR table_row IN
        SELECT * FROM (VALUES
            ('contractors', 'contractors'),
            ('contractor_insurance', 'insurance'),
            ('contractor_insurance_history', 'insurance'),
            ('projects', 'projects'),
            ('contractor_projects', 'projects'),
            ('contractor_tiered_subs', 'contractors'),
            ('compliance_types', 'compliance'),
            ('compliance_records', 'compliance'),
            ('documents', 'documents'),
            ('activity_log', 'activity'),
            ('contractor_followups', 'followups'),
            ('reminders', 'compliance'),
            ('import_history', 'imports')
        ) AS tables(table_name, module_name)
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_row.table_name);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (public.user_has_module_permission(%L, %L))', table_row.table_name || '_role_select', table_row.table_name, table_row.module_name, 'view');
        EXECUTE format('CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK (public.user_has_module_permission(%L, %L))', table_row.table_name || '_role_insert', table_row.table_name, table_row.module_name, 'manage');
        EXECUTE format('CREATE POLICY %I ON public.%I FOR UPDATE TO authenticated USING (public.user_has_module_permission(%L, %L)) WITH CHECK (public.user_has_module_permission(%L, %L))', table_row.table_name || '_role_update', table_row.table_name, table_row.module_name, 'manage', table_row.module_name, 'manage');
        EXECUTE format('CREATE POLICY %I ON public.%I FOR DELETE TO authenticated USING (public.user_has_module_permission(%L, %L))', table_row.table_name || '_role_delete', table_row.table_name, table_row.module_name, 'manage');
        EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', table_row.table_name);
        EXECUTE format('REVOKE ALL ON public.%I FROM anon', table_row.table_name);
        IF pg_get_serial_sequence('public.' || table_row.table_name, 'id') IS NOT NULL THEN
            EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', pg_get_serial_sequence('public.' || table_row.table_name, 'id'));
        END IF;
    END LOOP;

END;
$$;

CREATE OR REPLACE FUNCTION public.audit_application_change()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    actor UUID := auth.uid();
    actor_name TEXT;
    actor_email TEXT;
    old_values JSONB := '{}'::JSONB;
    new_values JSONB := '{}'::JSONB;
    changed_fields JSONB;
    target_id TEXT;
    target_label TEXT;
BEGIN
    IF TG_OP <> 'INSERT' THEN old_values := to_jsonb(OLD); END IF;
    IF TG_OP <> 'DELETE' THEN new_values := to_jsonb(NEW); END IF;

    IF TG_OP = 'INSERT' THEN
        SELECT COALESCE(jsonb_agg(field_name), '[]'::JSONB) INTO changed_fields FROM jsonb_object_keys(new_values) AS fields(field_name);
    ELSIF TG_OP = 'DELETE' THEN
        SELECT COALESCE(jsonb_agg(field_name), '[]'::JSONB) INTO changed_fields FROM jsonb_object_keys(old_values) AS fields(field_name);
    ELSE
        SELECT COALESCE(jsonb_agg(new_field.field_name), '[]'::JSONB) INTO changed_fields
        FROM jsonb_object_keys(new_values) AS new_field(field_name)
        WHERE (old_values -> new_field.field_name) IS DISTINCT FROM (new_values -> new_field.field_name);
    END IF;

    target_id := COALESCE(new_values ->> 'id', old_values ->> 'id', new_values ->> 'contractor_id', old_values ->> 'contractor_id', 'unknown');
    target_label := COALESCE(new_values ->> 'company_name', old_values ->> 'company_name', new_values ->> 'name', old_values ->> 'name', TG_TABLE_NAME || ':' || target_id);

    IF actor IS NOT NULL THEN
        SELECT name, email INTO actor_name, actor_email FROM public.user_profiles WHERE auth_user_id = actor;
        INSERT INTO public.administration_audit_log (user_id, user_name, user_email, action, object_type, object_id, object_label, details)
        VALUES (actor, COALESCE(actor_name, 'Unknown user'), COALESCE(actor_email, ''), TG_OP, TG_TABLE_NAME, target_id, target_label, jsonb_build_object('changed_fields', changed_fields));
    END IF;

    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.audit_application_change() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS audit_contractors_changes ON public.contractors;
CREATE TRIGGER audit_contractors_changes AFTER INSERT OR UPDATE OR DELETE ON public.contractors FOR EACH ROW EXECUTE FUNCTION public.audit_application_change();
DROP TRIGGER IF EXISTS audit_compliance_changes ON public.compliance_records;
CREATE TRIGGER audit_compliance_changes AFTER INSERT OR UPDATE OR DELETE ON public.compliance_records FOR EACH ROW EXECUTE FUNCTION public.audit_application_change();
DROP TRIGGER IF EXISTS audit_insurance_changes ON public.contractor_insurance;
CREATE TRIGGER audit_insurance_changes AFTER INSERT OR UPDATE OR DELETE ON public.contractor_insurance FOR EACH ROW EXECUTE FUNCTION public.audit_application_change();
DROP TRIGGER IF EXISTS audit_insurance_history_changes ON public.contractor_insurance_history;
CREATE TRIGGER audit_insurance_history_changes AFTER INSERT OR UPDATE OR DELETE ON public.contractor_insurance_history FOR EACH ROW EXECUTE FUNCTION public.audit_application_change();
DROP TRIGGER IF EXISTS audit_followup_changes ON public.contractor_followups;
CREATE TRIGGER audit_followup_changes AFTER INSERT OR UPDATE OR DELETE ON public.contractor_followups FOR EACH ROW EXECUTE FUNCTION public.audit_application_change();
DROP TRIGGER IF EXISTS audit_import_changes ON public.import_history;
CREATE TRIGGER audit_import_changes AFTER INSERT OR UPDATE OR DELETE ON public.import_history FOR EACH ROW EXECUTE FUNCTION public.audit_application_change();

COMMIT;
