BEGIN;

CREATE TABLE IF NOT EXISTS contractor_tiered_subs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contractor_id INTEGER NOT NULL,
    tiered_sub_contractor_id INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    assigned_date DATE NOT NULL DEFAULT CURRENT_DATE,
    removed_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_contractor_tiered_subs_contractor
        FOREIGN KEY (contractor_id) REFERENCES contractors(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_contractor_tiered_subs_tiered_sub_contractor
        FOREIGN KEY (tiered_sub_contractor_id) REFERENCES contractors(id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_contractor_tiered_subs_not_self
        CHECK (contractor_id <> tiered_sub_contractor_id),
    CONSTRAINT chk_contractor_tiered_subs_dates
        CHECK (removed_date IS NULL OR removed_date >= assigned_date)
);

CREATE INDEX IF NOT EXISTS idx_contractor_tiered_subs_contractor_id
    ON contractor_tiered_subs (contractor_id);

CREATE INDEX IF NOT EXISTS idx_contractor_tiered_subs_tiered_sub_contractor_id
    ON contractor_tiered_subs (tiered_sub_contractor_id);

CREATE INDEX IF NOT EXISTS idx_contractor_tiered_subs_active
    ON contractor_tiered_subs (active);

-- Only one active relationship allowed per contractor/tiered-sub pair; history is preserved via inactive rows.
CREATE UNIQUE INDEX IF NOT EXISTS uq_contractor_tiered_subs_active
    ON contractor_tiered_subs (contractor_id, tiered_sub_contractor_id)
    WHERE active = TRUE;

ALTER TABLE contractor_tiered_subs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS contractor_tiered_subs_select_development ON contractor_tiered_subs;
CREATE POLICY contractor_tiered_subs_select_development
    ON contractor_tiered_subs FOR SELECT
    TO anon, authenticated
    USING (TRUE);

DROP POLICY IF EXISTS contractor_tiered_subs_insert_development ON contractor_tiered_subs;
CREATE POLICY contractor_tiered_subs_insert_development
    ON contractor_tiered_subs FOR INSERT
    TO anon, authenticated
    WITH CHECK (TRUE);

DROP POLICY IF EXISTS contractor_tiered_subs_update_development ON contractor_tiered_subs;
CREATE POLICY contractor_tiered_subs_update_development
    ON contractor_tiered_subs FOR UPDATE
    TO anon, authenticated
    USING (TRUE)
    WITH CHECK (TRUE);

COMMIT;
