BEGIN;

CREATE TABLE IF NOT EXISTS contractor_insurance (
    contractor_id INTEGER PRIMARY KEY,
    certificate_on_file BOOLEAN NOT NULL DEFAULT FALSE,
    last_verified_date DATE,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_contractor_insurance_contractor
        FOREIGN KEY (contractor_id) REFERENCES contractors(id)
        ON DELETE RESTRICT
);

ALTER TABLE contractor_insurance
    DROP COLUMN IF EXISTS mycoi_vendor_id;

CREATE TABLE IF NOT EXISTS contractor_insurance_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contractor_id INTEGER NOT NULL,
    coi_on_file BOOLEAN NOT NULL,
    verified_date DATE,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_contractor_insurance_history_contractor
        FOREIGN KEY (contractor_id) REFERENCES contractors(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_contractor_insurance_history_contractor_created
    ON contractor_insurance_history (contractor_id, created_at DESC);

INSERT INTO compliance_types (compliance_name, requires_expiration, active)
VALUES
    ('NJ PWC', TRUE, TRUE),
    ('NJ BRC', FALSE, TRUE),
    ('NY PWC', TRUE, TRUE),
    ('NY BRC', FALSE, TRUE),
    ('W9', FALSE, TRUE),
    ('Safety Certification', TRUE, TRUE)
ON CONFLICT (compliance_name) DO UPDATE
SET requires_expiration = EXCLUDED.requires_expiration,
    active = TRUE;

UPDATE compliance_types
SET active = FALSE
WHERE compliance_name IN ('Insurance Certificate', 'Public Works Registration', 'Business Registration');

ALTER TABLE compliance_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE contractor_insurance ENABLE ROW LEVEL SECURITY;
ALTER TABLE contractor_insurance_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS compliance_types_select_development ON compliance_types;
CREATE POLICY compliance_types_select_development
    ON compliance_types FOR SELECT
    TO anon, authenticated
    USING (TRUE);

DROP POLICY IF EXISTS contractor_insurance_select_development ON contractor_insurance;
CREATE POLICY contractor_insurance_select_development
    ON contractor_insurance FOR SELECT
    TO anon, authenticated
    USING (TRUE);

DROP POLICY IF EXISTS contractor_insurance_insert_development ON contractor_insurance;
CREATE POLICY contractor_insurance_insert_development
    ON contractor_insurance FOR INSERT
    TO anon, authenticated
    WITH CHECK (TRUE);

DROP POLICY IF EXISTS contractor_insurance_update_development ON contractor_insurance;
CREATE POLICY contractor_insurance_update_development
    ON contractor_insurance FOR UPDATE
    TO anon, authenticated
    USING (TRUE)
    WITH CHECK (TRUE);

DROP POLICY IF EXISTS contractor_insurance_history_select_development ON contractor_insurance_history;
CREATE POLICY contractor_insurance_history_select_development
    ON contractor_insurance_history FOR SELECT
    TO anon, authenticated
    USING (TRUE);

DROP POLICY IF EXISTS contractor_insurance_history_insert_development ON contractor_insurance_history;
CREATE POLICY contractor_insurance_history_insert_development
    ON contractor_insurance_history FOR INSERT
    TO anon, authenticated
    WITH CHECK (TRUE);

COMMIT;