-- =====================================================================
-- Compliance Sync Administration module
-- Date: 2026-10-02
--
-- Administrative foundation for future NJ/NY compliance verification
-- (Manual verification, RPA workflow, API integration).
--
-- =====================================================================
-- COMPLIANCE LOGIC LOCK
-- =====================================================================
-- Active Compliance Records (compliance_records.expiration_date via the
-- contractor_compliance_status view) remain the AUTHORITATIVE and SOLE
-- source for: Expired / 90 / 60 / 30 Day buckets, Missing Information,
-- dashboard counts, contractor status, reports, and reminders.
--
-- The tables below store sync RUN metadata, review queue entries,
-- settings, and exceptions for FUTURE verification pipelines. None of
-- them are read by any compliance calculation, count, status, report,
-- or reminder path. They are informational / administrative only.
--
-- FUTURE PREPARATION (do NOT implement now):
--   IF an Administrator approves a review-queue entry
--   THEN update the matching Active Compliance Record.
--   or
--   IF compliance_sync_settings.mode = 'auto_approve' (or the record's
--   sync_source = 'API')
--   THEN the Active Compliance Record may eventually be auto-updated.
--   Until that behavior is intentionally built, approving/rejecting
--   entries here has NO effect on compliance status.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. Settings: one row per syncable compliance type
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.compliance_sync_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compliance_name VARCHAR(20) NOT NULL UNIQUE
        CHECK (compliance_name IN ('NJ PWC', 'NJ BRC', 'NY PWC', 'NY BRC')),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    -- 'review_required' = entries go to the review queue (default)
    -- 'auto_approve'    = reserved for future auto-approval (not yet active)
    mode VARCHAR(20) NOT NULL DEFAULT 'review_required'
        CHECK (mode IN ('review_required', 'auto_approve')),
    sync_source VARCHAR(10) NOT NULL DEFAULT 'Manual'
        CHECK (sync_source IN ('Manual', 'RPA', 'API')),
    schedule_cron VARCHAR(100),
    last_sync_at TIMESTAMPTZ,
    next_sync_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed the four syncable compliance types
INSERT INTO public.compliance_sync_settings (compliance_name, enabled, mode, sync_source)
VALUES
    ('NJ PWC', TRUE, 'review_required', 'Manual'),
    ('NJ BRC', TRUE, 'review_required', 'Manual'),
    ('NY PWC', TRUE, 'review_required', 'Manual'),
    ('NY BRC', TRUE, 'review_required', 'Manual')
ON CONFLICT (compliance_name) DO NOTHING;

-- ---------------------------------------------------------------------
-- 2. Sync runs: batch history (powers Last Sync / Records Checked /
--    Changes Detected summary cards)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.compliance_sync_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sync_source VARCHAR(10) NOT NULL DEFAULT 'Manual'
        CHECK (sync_source IN ('Manual', 'RPA', 'API')),
    status VARCHAR(20) NOT NULL DEFAULT 'completed'
        CHECK (status IN ('completed', 'completed_with_errors', 'failed')),
    records_checked INTEGER NOT NULL DEFAULT 0 CHECK (records_checked >= 0),
    changes_detected INTEGER NOT NULL DEFAULT 0 CHECK (changes_detected >= 0),
    records_approved INTEGER NOT NULL DEFAULT 0 CHECK (records_approved >= 0),
    records_rejected INTEGER NOT NULL DEFAULT 0 CHECK (records_rejected >= 0),
    failures INTEGER NOT NULL DEFAULT 0 CHECK (failures >= 0),
    triggered_by VARCHAR(200),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_compliance_sync_runs_run_at
    ON public.compliance_sync_runs (run_at DESC);

-- ---------------------------------------------------------------------
-- 3. Review queue: per-record entries pending admin decision
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.compliance_sync_review_queue (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_run_id INTEGER REFERENCES public.compliance_sync_runs(id) ON DELETE SET NULL,
    contractor_id INTEGER NOT NULL REFERENCES public.contractors(id) ON DELETE CASCADE,
    compliance_record_id INTEGER REFERENCES public.compliance_records(id) ON DELETE SET NULL,
    compliance_name VARCHAR(20) NOT NULL
        CHECK (compliance_name IN ('NJ PWC', 'NJ BRC', 'NY PWC', 'NY BRC')),
    -- Proposed (synced) values
    proposed_registration_number VARCHAR(200),
    proposed_status VARCHAR(100),
    proposed_expiration_date DATE,
    -- Current (authoritative) values snapshot for side-by-side review
    current_registration_number VARCHAR(200),
    current_expiration_date DATE,
    -- Review state
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'approved', 'rejected')),
    sync_source VARCHAR(10) NOT NULL DEFAULT 'Manual'
        CHECK (sync_source IN ('Manual', 'RPA', 'API')),
    reviewed_by VARCHAR(200),
    reviewed_at TIMESTAMPTZ,
    review_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_compliance_sync_review_queue_status
    ON public.compliance_sync_review_queue (status, created_at DESC);

-- ---------------------------------------------------------------------
-- 4. Exceptions: failed / anomalous verification attempts
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.compliance_sync_exceptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_run_id INTEGER REFERENCES public.compliance_sync_runs(id) ON DELETE SET NULL,
    contractor_id INTEGER REFERENCES public.contractors(id) ON DELETE CASCADE,
    compliance_name VARCHAR(20) CHECK (compliance_name IN ('NJ PWC', 'NJ BRC', 'NY PWC', 'NY BRC')),
    exception_type VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_by VARCHAR(200),
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_compliance_sync_exceptions_resolved
    ON public.compliance_sync_exceptions (resolved, created_at DESC);

-- ---------------------------------------------------------------------
-- 5. Row Level Security (development-permissive, consistent with other
--    tables; tighten with user_has_module_permission in a later pass)
-- ---------------------------------------------------------------------
ALTER TABLE public.compliance_sync_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compliance_sync_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compliance_sync_review_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compliance_sync_exceptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS compliance_sync_settings_select ON public.compliance_sync_settings;
CREATE POLICY compliance_sync_settings_select ON public.compliance_sync_settings FOR SELECT TO authenticated USING (TRUE);
DROP POLICY IF EXISTS compliance_sync_settings_insert ON public.compliance_sync_settings;
CREATE POLICY compliance_sync_settings_insert ON public.compliance_sync_settings FOR INSERT TO authenticated WITH CHECK (TRUE);
DROP POLICY IF EXISTS compliance_sync_settings_update ON public.compliance_sync_settings;
CREATE POLICY compliance_sync_settings_update ON public.compliance_sync_settings FOR UPDATE TO authenticated USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS compliance_sync_runs_select ON public.compliance_sync_runs;
CREATE POLICY compliance_sync_runs_select ON public.compliance_sync_runs FOR SELECT TO authenticated USING (TRUE);
DROP POLICY IF EXISTS compliance_sync_runs_insert ON public.compliance_sync_runs;
CREATE POLICY compliance_sync_runs_insert ON public.compliance_sync_runs FOR INSERT TO authenticated WITH CHECK (TRUE);
DROP POLICY IF EXISTS compliance_sync_runs_update ON public.compliance_sync_runs;
CREATE POLICY compliance_sync_runs_update ON public.compliance_sync_runs FOR UPDATE TO authenticated USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS compliance_sync_review_queue_select ON public.compliance_sync_review_queue;
CREATE POLICY compliance_sync_review_queue_select ON public.compliance_sync_review_queue FOR SELECT TO authenticated USING (TRUE);
DROP POLICY IF EXISTS compliance_sync_review_queue_insert ON public.compliance_sync_review_queue;
CREATE POLICY compliance_sync_review_queue_insert ON public.compliance_sync_review_queue FOR INSERT TO authenticated WITH CHECK (TRUE);
DROP POLICY IF EXISTS compliance_sync_review_queue_update ON public.compliance_sync_review_queue;
CREATE POLICY compliance_sync_review_queue_update ON public.compliance_sync_review_queue FOR UPDATE TO authenticated USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS compliance_sync_exceptions_select ON public.compliance_sync_exceptions;
CREATE POLICY compliance_sync_exceptions_select ON public.compliance_sync_exceptions FOR SELECT TO authenticated USING (TRUE);
DROP POLICY IF EXISTS compliance_sync_exceptions_insert ON public.compliance_sync_exceptions;
CREATE POLICY compliance_sync_exceptions_insert ON public.compliance_sync_exceptions FOR INSERT TO authenticated WITH CHECK (TRUE);
DROP POLICY IF EXISTS compliance_sync_exceptions_update ON public.compliance_sync_exceptions;
CREATE POLICY compliance_sync_exceptions_update ON public.compliance_sync_exceptions FOR UPDATE TO authenticated USING (TRUE) WITH CHECK (TRUE);

-- ---------------------------------------------------------------------
-- 6. Grant the new module permission
-- ---------------------------------------------------------------------
-- Expand the module CHECK to include compliance_sync
ALTER TABLE public.role_permissions DROP CONSTRAINT IF EXISTS role_permissions_module_check;
ALTER TABLE public.role_permissions ADD CONSTRAINT role_permissions_module_check
    CHECK (module IN ('dashboard', 'contractors', 'compliance', 'insurance', 'followups', 'projects', 'tiered_subs', 'reports', 'imports', 'documents', 'activity', 'users', 'roles', 'audit', 'settings', 'compliance_sync'));

-- Full access for Administrator (unconditional: insert if missing,
-- force-update to full access if it already exists with reduced flags)
INSERT INTO public.role_permissions (role, module, can_view, can_manage, can_add, can_edit, can_delete)
VALUES ('Administrator', 'compliance_sync', TRUE, TRUE, TRUE, TRUE, TRUE)
ON CONFLICT (role, module) DO UPDATE
SET can_view = TRUE, can_manage = TRUE, can_add = TRUE, can_edit = TRUE, can_delete = TRUE;

-- Default NO access for every other role (grant individually via Role Management)
INSERT INTO public.role_permissions (role, module, can_view, can_manage, can_add, can_edit, can_delete)
SELECT DISTINCT rp.role, 'compliance_sync', FALSE, FALSE, FALSE, FALSE, FALSE
FROM public.role_permissions rp
WHERE rp.role <> 'Administrator'
  AND NOT EXISTS (
      SELECT 1 FROM public.role_permissions existing
      WHERE existing.role = rp.role AND existing.module = 'compliance_sync'
  );

COMMIT;

-- Review: module access by role
SELECT role, can_view, can_manage FROM public.role_permissions WHERE module = 'compliance_sync' ORDER BY role;
