project_id = "subtracker"

[auth.email.template.invite]
subject = "You're Invited to Access SubTracker"
content_path = "./supabase/templates/invite.html"

[auth.email.template.recovery]
subject = "Reset Your SubTracker Password"
content_path = "./supabase/templates/recovery.html"
