-- WARNING: Running this script again will delete all existing SubTracker data.
DROP VIEW IF EXISTS contractor_compliance_status;

DROP TABLE IF EXISTS import_history CASCADE;
DROP TABLE IF EXISTS reminders CASCADE;
DROP TABLE IF EXISTS activity_log CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS compliance_records CASCADE;
DROP TABLE IF EXISTS compliance_types CASCADE;
DROP TABLE IF EXISTS contractor_projects CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS contractors CASCADE;

CREATE TABLE contractors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(200) NOT NULL,
    trade VARCHAR(150),
    contact_name VARCHAR(200),
    email VARCHAR(200),
    phone VARCHAR(50),
    notes TEXT,
    external_id VARCHAR(100),
    legacy_id VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_number VARCHAR(100) NOT NULL UNIQUE,
    project_name VARCHAR(200) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active', 'Pending', 'Completed', 'On Hold', 'Cancelled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE contractor_projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contractor_id INTEGER NOT NULL,
    project_id INTEGER NOT NULL,
    assigned_date DATE NOT NULL DEFAULT CURRENT_DATE,
    removed_date DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_contractor_projects_contractor
        FOREIGN KEY (contractor_id) REFERENCES contractors(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_contractor_projects_project
        FOREIGN KEY (project_id) REFERENCES projects(id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_contractor_project_dates
        CHECK (removed_date IS NULL OR removed_date >= assigned_date)
);

CREATE TABLE compliance_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compliance_name VARCHAR(200) NOT NULL UNIQUE,
    requires_expiration BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO compliance_types (compliance_name, requires_expiration, active)
VALUES
    ('NJ PWC', TRUE, TRUE),
    ('NJ BRC', FALSE, TRUE),
    ('NY PWC', TRUE, TRUE),
    ('NY BRC', FALSE, TRUE),
    ('Insurance Certificate', TRUE, TRUE),
    ('W9', FALSE, TRUE),
    ('Safety Certification', TRUE, TRUE);

CREATE TABLE compliance_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contractor_id INTEGER NOT NULL,
    compliance_type_id INTEGER NOT NULL,
    registration_number VARCHAR(200),
    effective_date DATE,
    expiration_date DATE,
    verified_date DATE,
    verified_by VARCHAR(200),
    verification_source VARCHAR(100),
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_compliance_records_contractor
        FOREIGN KEY (contractor_id) REFERENCES contractors(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_compliance_records_type
        FOREIGN KEY (compliance_type_id) REFERENCES compliance_types(id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_compliance_dates
        CHECK (
            expiration_date IS NULL
            OR effective_date IS NULL
            OR expiration_date >= effective_date
        )
);

CREATE TABLE documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contractor_id INTEGER NOT NULL,
    compliance_record_id INTEGER,
    document_name VARCHAR(200) NOT NULL,
    document_type VARCHAR(100) NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    original_file_name VARCHAR(255),
    storage_provider VARCHAR(50),
    file_size_bytes BIGINT CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
    upload_date DATE NOT NULL DEFAULT CURRENT_DATE,
    expiration_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_documents_contractor
        FOREIGN KEY (contractor_id) REFERENCES contractors(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_documents_compliance_record
        FOREIGN KEY (compliance_record_id) REFERENCES compliance_records(id)
        ON DELETE RESTRICT
);

CREATE TABLE activity_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contractor_id INTEGER NOT NULL,
    project_id INTEGER,
    activity_date DATE NOT NULL DEFAULT CURRENT_DATE,
    activity_type VARCHAR(100) NOT NULL,
    notes TEXT,
    follow_up_date DATE,
    created_by VARCHAR(200),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_activity_log_contractor
        FOREIGN KEY (contractor_id) REFERENCES contractors(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_activity_log_project
        FOREIGN KEY (project_id) REFERENCES projects(id)
        ON DELETE RESTRICT
);

CREATE TABLE reminders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contractor_id INTEGER NOT NULL,
    compliance_record_id INTEGER NOT NULL,
    reminder_stage VARCHAR(20) NOT NULL
        CHECK (reminder_stage IN ('90 Day', '60 Day', '30 Day', 'Expired')),
    expiration_date_snapshot DATE NOT NULL,
    scheduled_date DATE NOT NULL,
    generated_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_date TIMESTAMPTZ,
    delivery_status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    acknowledged_date TIMESTAMPTZ,
    resolved_date TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_reminders_contractor
        FOREIGN KEY (contractor_id) REFERENCES contractors(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_reminders_compliance_record
        FOREIGN KEY (compliance_record_id) REFERENCES compliance_records(id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_reminders_stage_cycle UNIQUE (
        compliance_record_id,
        reminder_stage,
        expiration_date_snapshot
    )
);

CREATE TABLE import_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(250) NOT NULL,
    import_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    imported_rows INTEGER NOT NULL DEFAULT 0 CHECK (imported_rows >= 0),
    successful_rows INTEGER NOT NULL DEFAULT 0 CHECK (successful_rows >= 0),
    failed_rows INTEGER NOT NULL DEFAULT 0 CHECK (failed_rows >= 0),
    notes TEXT,
    CONSTRAINT chk_import_history_consistency
        CHECK (successful_rows + failed_rows <= imported_rows)
);

CREATE INDEX idx_contractors_company_name
    ON contractors (company_name);

CREATE INDEX idx_contractors_external_id
    ON contractors (external_id);

CREATE INDEX idx_projects_project_number
    ON projects (project_number);

CREATE INDEX idx_contractor_projects_contractor_id
    ON contractor_projects (contractor_id);

CREATE INDEX idx_contractor_projects_project_id
    ON contractor_projects (project_id);

CREATE UNIQUE INDEX uq_contractor_project_active
    ON contractor_projects (contractor_id, project_id)
    WHERE active = TRUE;

CREATE INDEX idx_compliance_records_expiration_date
    ON compliance_records (expiration_date);

CREATE INDEX idx_compliance_records_current
    ON compliance_records (is_current, active);

CREATE INDEX idx_compliance_records_contractor_id
    ON compliance_records (contractor_id);

CREATE INDEX idx_compliance_records_type_id
    ON compliance_records (compliance_type_id);

CREATE INDEX idx_documents_contractor_id
    ON documents (contractor_id);

CREATE INDEX idx_documents_compliance_record_id
    ON documents (compliance_record_id);

CREATE INDEX idx_activity_log_contractor_id
    ON activity_log (contractor_id);

CREATE INDEX idx_activity_log_follow_up_date
    ON activity_log (follow_up_date);

CREATE INDEX idx_reminders_compliance_record_expiration_stage
    ON reminders (compliance_record_id, expiration_date_snapshot, reminder_stage);

CREATE INDEX idx_reminders_scheduled_date
    ON reminders (scheduled_date);

CREATE INDEX idx_reminders_unresolved
    ON reminders (resolved_date, delivery_status)
    WHERE resolved_date IS NULL;

CREATE INDEX idx_import_history_import_date
    ON import_history (import_date);

CREATE VIEW contractor_compliance_status
WITH (security_invoker = true) AS
SELECT
    c.id AS contractor_id,
    c.company_name,
    c.active AS contractor_active,
    cr.active AS compliance_active,
    cr.is_current AS compliance_current,
    cr.id AS compliance_record_id,
    ct.id AS compliance_type_id,
    ct.compliance_name,
    cr.registration_number,
    cr.expiration_date,
    CASE
        WHEN cr.id IS NULL THEN NULL
        WHEN cr.expiration_date IS NULL THEN NULL
        ELSE (cr.expiration_date - CURRENT_DATE)::INTEGER
    END AS days_remaining,
    CASE
        WHEN cr.id IS NULL THEN 'Missing Information'
        WHEN ct.requires_expiration = TRUE AND cr.expiration_date IS NULL THEN 'Missing Information'
        WHEN ct.compliance_name IN ('NJ PWC', 'NY PWC')
            AND NULLIF(TRIM(cr.registration_number), '') IS NULL THEN 'Missing Information'
        WHEN cr.expiration_date <= CURRENT_DATE THEN 'Expired'
        WHEN (cr.expiration_date - CURRENT_DATE) BETWEEN 1 AND 30 THEN '30 Day'
        WHEN (cr.expiration_date - CURRENT_DATE) BETWEEN 31 AND 60 THEN '60 Day'
        WHEN (cr.expiration_date - CURRENT_DATE) BETWEEN 61 AND 90 THEN '90 Day'
        WHEN cr.expiration_date IS NULL AND ct.requires_expiration = FALSE THEN 'Active'
        WHEN (cr.expiration_date - CURRENT_DATE) > 90 THEN 'Active'
        ELSE 'Active'
    END AS calculated_status
FROM contractors c
LEFT JOIN compliance_records cr
    ON cr.contractor_id = c.id
   AND cr.active = TRUE
   AND cr.is_current = TRUE
LEFT JOIN compliance_types ct
    ON ct.id = cr.compliance_type_id
WHERE c.active = TRUE;

ALTER TABLE contractors ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE contractor_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE compliance_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE compliance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE import_history ENABLE ROW LEVEL SECURITY;
